.TH quickMacro 1 "quickMacro VERSION"
.SH NAME
\fBquickMacro\fR - a simple and fast macro program
.SH SYNOPSIS
\fBquickMacro\fR \fB-r\fR|\fB-p\fR [\fB-l\fR] \fIfile\fR
.SH DESCRIPTION
Record or play macros to or from \fIfile\fR
.SH OPTIONS
.TP
.B -r, --record
Wait for QUITKEY to be pressed and then start recording
until QUITKEY is pressed again. The time of the first
QUITKEY press is the zero time offset for the macro.
.TP
.B -p, --play
Play back the macro by sending all events as XTEST requests.
.TP
.B -l, --loop
Play the macro until QUITKEY is pressed.
.SH IMPORTANT CONSIDERATIONS
Each event takes up 32 bytes in the macro file. Mouse events
occur at a high frequency and thus can quickly take up a lot
of space.

\fBquickMacro\fR may take a while to stop after QUITKEY is
pressed

The time between each loop of the macro is the time between
starting recording and the first event recorded.
.SH EXIT STATUS
.TP
.B -1
Unknown event type
.TP
.B 11
X server connect failed or extension is not running
.TP
.B 21
File is specified is not regular
.TP
.B 22
Argument error
.SH CUSTOMIZATION
\fBquickMacro\fR can be customized by editing QUITKEY under
\fI/* config */\fR near the top of the source, and
recompiling.

QUITKEY is the keycode of the key that starts and ends
macro recording. It is set to the US right super key by
default.
